"""
Django settings for personal_portfolio project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# django_heroku removed - not needed for PythonAnywhere deployment

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect if running on PythonAnywhere
ON_PYTHONANYWHERE = os.environ.get('PYTHONANYWHERE_DOMAIN', '').endswith('.pythonanywhere.com')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if ON_PYTHONANYWHERE:
    # Production: get from environment variable
    SECRET_KEY = os.environ.get('SECRET_KEY', 'CHANGE-THIS-IN-PRODUCTION-ENV-VARS')
    DEBUG = False
else:
    # Development: use default (not secure, but OK for local)
    SECRET_KEY = "django-insecure-x(b^d1_90*3v&6sn&hd*lm07r3-1v=pmw^jza!$4n2m5#wgt*b"
    DEBUG = True

# SECURITY WARNING: don't run with debug turned on in production!
if ON_PYTHONANYWHERE:
    ALLOWED_HOSTS = ['Vasile70Tanasa.eu.pythonanywhere.com', 'www.Vasile70Tanasa.eu.pythonanywhere.com']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# OpenAI API Key (optional - for chatbot)
# Method 1: Set as environment variable (RECOMMENDED):
#   Windows PowerShell: $env:OPENAI_API_KEY="sk-your-key-here"
#   Linux/Mac: export OPENAI_API_KEY="sk-your-key-here"
#
# Method 2: Set directly here (ONLY for local development, NOT for production):
#   Uncomment the line below and add your API key:
# OPENAI_API_KEY = "sk-your-api-key-here"
#
# The code will check environment variable first, then settings.OPENAI_API_KEY


# Application definition

INSTALLED_APPS = [
    "pages.apps.PagesConfig",
    "projects.apps.ProjectsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django_heroku removed - not needed for PythonAnywhere
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "personal_portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates/",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "personal_portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS - Django will automatically find static files in app/static/ directories
# No need to specify since we're using app-level static directories (pages/static, projects/static)

MEDIA_ROOT = BASE_DIR / "uploads/"
MEDIA_URL = "media/"

# Static files storage - using default for development and production
# For PythonAnywhere, you can use ManifestStaticFilesStorage in production if needed
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
