# Generated by Django 4.1.5 on 2023-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="link", field=models.URLField(default=""),
        ),
    ]
